{% set name = "west" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/west-{{ version }}.tar.gz
  sha256: 66f870221928112ef58f2bfc5efd1d778e19eed140673984d97b221fbc0525f4

build:
  entry_points:
    - west = west.app.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - colorama
    - pyyaml >=5.1
    - pykwalify
    - setuptools
    - packaging

test:
  imports:
    - west
  commands:
    - pip check
    - west --help
  requires:
    - pip

about:
  home: https://github.com/zephyrproject-rtos/west
  summary: Zephyr RTOS Project meta-tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
