{% set name = "west" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/west-{{ version }}.tar.gz
  sha256: 89320034be87099d16e75f4760ac0d1ed67e8978928e468ab993e3fba0cfe92f

build:
  entry_points:
    - west = west.app.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - colorama
    - pyyaml >=5.1
    - pykwalify
    - setuptools
    - packaging

test:
  imports:
    - west
  commands:
    - pip check
    - west --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zephyrproject-rtos/west
  summary: Zephyr RTOS Project meta-tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
